### PR TITLE
Development calc fixes

### PR DESCRIPTION
**Pull request by timurgordon**
Fixes to baobab, mostly to follow the new implementation of actionsparser in crystallib. Added contact methods implementation, tests are working, and optimized.

### CODE REVIEW

**Comment by brandonpille** [comment]
This PR was merged into development while the tests were failing. There is a reason why we have the tests. They should be green before merging into development! As a result of this merge the farmerbot is no longer building because baobab is no longer building for development in crystallib.

**Comment by timurgordon** [comment]
Hi, it is unfortunate that it was merged to development. Development_calc was failing the tests independent from the changes i had made, as it was mostly something that was under development, with code written halfway, so I didn’t really bother with the tests running successfully, since it wasn’t caused from the branch being merging. I’ll have greater concern for making sure that the necessary fixes to the base branch are made before merging pr's.

**Comment by timurgordon** [comment]
Should we consider having stricter merging policies on the development branch to prevent this from happening again?

**Comment by brandonpille** [comment]
Yes we should make the development branch protected. Unfortunately I can't do that, I don't have enough permissions. Kristof is the creator of this repository so he will be able to do that. Or give us more permissions.

**Pull request merged**
